### ISSUE TITLE
[BUG] Slow performance when files modified

### ISSUE THREAD

**Issue by technotherion** [franciskafieh/obsidian-list-modified#101] opened 2024-08-18 17:52 UTC
Forgive the vague nature of my report. If this is not helpful I can gather more information. 

## First Steps

-   [x] I've ensured that the issue **does not already exist** by [using the search feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified
-   [x] I'm on the latest release of Obsidian
-   [ ] I've tried disabling any other plugins that may cause conflicts (optional but recommended)
   - I intend on trying this in a testing vault later to help narrow down some things such as vault size and plugins. 
   - I know for sure that Linter is not causing this issue, which was my first suspicion. 

## Describe the bug

When a document is first modified, Obsidian freezes up for a few moments. 
When the Write Interval was set to 0, performance issues made it extremely difficult to write notes as Obsidian would lock up every few seconds. I set the Write Interval to 3000 and this has helped considerably. 

I am assuming that the freeze is caused the plugin is writing into the modified section of the note that I have my Modify List in. 

## Expected behaviour / suggestions? 

- Compare date of note modification with the new date to be written. If the date is the same, do not rewrite. (I do not know if this already happens.) 
   - Maybe it would be helpful to ignore notes if their date/hour has not passed yet. 
   - Option to ignore or limit to only hh as the smallest time measurement so that the file only gets written to at most once an hour. 
- Wait until the file is manually saved or tab switched before saving the modified date to the list (a la Linter)

### My setup

I am syncing my notes via DropBox using the default Windows client. 
My vault contains 3,496 files.

**Comment by franciskafieh** [comment] 2024-08-18 18:16
Can you try to reproduce this bug while in verbose mode under the plugin's settings? After you turn that on, open ctrl+shift+i then go to console and try to get it to lag. Please screenshot the console messages you get when Obsidian lags. I basically want to know if the lag is caused by many file modifications at once (sync issue, I see you're using dropbox) or something else

**Comment by technotherion** [comment] 2024-08-19 14:15
Sure thing -- will add this to my todo list. Please poke me if you do not hear back by the end of the week.

**Comment by franciskafieh** [comment] 2024-08-31 14:04
Any updates on this?

**Comment by franciskafieh** [comment] 2024-09-06 19:48
Closing since no updates

**Closed by franciskafieh** 2024-09-06 19:48 UTC
Labels: question
