### ISSUE TITLE
Odd behavior when notes are duplicated

### ISSUE THREAD

**Issue by ScottKillen** [franciskafieh/obsidian-list-modified#12] opened 2022-04-04 02:01 UTC
If I make a copy of a note using the file explorer context menu, a second link to the original file is added to the daily note. The expected behavior would be to add a link to the **copy**.

**Comment by franciskafieh** [comment] 2022-04-04 03:12
Don't think the obsidian api would permit me to fix this... the modify event listener callback gives me a `TAbstractFile` and I simply use that... could be misunderstanding though

need some more time to look into this and consider if it's worth fixing (if even possible)

**Comment by ScottKillen** [comment] 2022-04-04 03:59
I probably should have described the behavior using a little more detail:

1.  Modify a file. (This puts a link in the daily note.)
2. Use the "make a copy" menu option on the same file. (This puts a **duplicate** link to the original file.)

So it would seem that in this case, `fileIsLinked()` is not detecting the link to the original file and a new duplicate link is being added to the daily note, _-or-_ `fileIsLinked()` is working and the modify event is maybe passing the wrong file on a copy.

I wonder if listening for the 'create' event would fix this? It seems that all created files should be added to the list anyway.

🤔

**Comment by ScottKillen** [comment] 2022-04-04 04:25
Did some more testing on the latest version:

1. Created a file called `test`.
2. Verified that the link appeared in the daily note. ✔️ 
3. Right clicked on `test` in the file explorer and selected "Make a copy"
4. Checked daily note, but no link was added for the new file. ❗ 
5. Selected the new file `test 1` in the file explorer.
6. Modified the file.
7. Checked the daily note, but no link is **ever** added for `test 1`, _even after_ editing other files which do get added to the daily note.

Console keeps spamming this everytime I modify the copy:

````
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'some')
    at ListModified.frontmatterMetadataContainsTag (eval at <anonymous> (app.js:1:1490278), <anonymous>:166:34)
    at ListModified.fileMeetsTagRequirements (eval at <anonymous> (app.js:1:1490278), <anonymous>:151:52)
    at ListModified.eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:119:17)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:46:61)
    at new Promise (<anonymous>)
    at __async (eval at <anonymous> (app.js:1:1490278), <anonymous>:30:10)
    at ListModified.onModify (eval at <anonymous> (app.js:1:1490278), <anonymous>:102:31)
    at t.e.tryTrigger (app.js:1:900700)
    at t.e.trigger (app.js:1:900633)
````

I have attached both of the referenced files.

- [test.md](https://github.com/franciskafieh/obsidian-list-modified/files/8406671/test.md)
- [test 1.md](https://github.com/franciskafieh/obsidian-list-modified/files/8406669/test.1.md)

Edits to `test.md` **always** get added to the daily note. Edits to its copy, `test 1.md` are _**never**_ added to the daily note.

**Comment by franciskafieh** [comment] 2022-04-04 11:02
might know how to fix this... will try when i get home from school

**Comment by franciskafieh** [comment] 2022-04-04 11:12
I suspect that the metadata cache i use to get links and tags from a file does not exist initially when you copy a file... explains the error in console

another issue is that i use the file's name to link to the daily note. this means that duplicate files will have the same link. there's got to be a better way... could try `getFirstLinkPath`, i think that's what it's for.

sorry i was unable to think straight yesterday & i said it couldn't be fixed lol. was super tired

**Comment by franciskafieh** [comment] 2022-04-04 19:21
use pjeby on the discord told me this...
![image](https://user-images.githubusercontent.com/93789670/161616586-9241c78a-af2a-4d0b-b87d-3a6710d62247.png)

would solve the wrong link part :D

**Comment by franciskafieh** [comment] 2022-04-04 21:49
> Did some more testing on the latest version:
> 
>     1. Created a file called `test`.
> 
>     2. Verified that the link appeared in the daily note. ✔️
> 
>     3. Right clicked on `test` in the file explorer and selected "Make a copy"
> 
>     4. Checked daily note, but no link was added for the new file. ❗
> 
>     5. Selected the new file `test 1` in the file explorer.
> 
>     6. Modified the file.
> 
>     7. Checked the daily note, but no link is **ever** added for `test 1`, _even after_ editing other files which do get added to the daily note.
> 
> 
> The console keeps spamming this every time I modify the copy:
> 
> ```
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'some')
>     at ListModified.frontmatterMetadataContainsTag (eval at <anonymous> (app.js:1:1490278), <anonymous>:166:34)
>     at ListModified.fileMeetsTagRequirements (eval at <anonymous> (app.js:1:1490278), <anonymous>:151:52)
>     at ListModified.eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:119:17)
>     at Generator.next (<anonymous>)
>     at eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:46:61)
>     at new Promise (<anonymous>)
>     at __async (eval at <anonymous> (app.js:1:1490278), <anonymous>:30:10)
>     at ListModified.onModify (eval at <anonymous> (app.js:1:1490278), <anonymous>:102:31)
>     at t.e.tryTrigger (app.js:1:900700)
>     at t.e.trigger (app.js:1:900633)
> ```
> 
> I have attached both of the referenced files.
> 
>     * [test.md](https://github.com/franciskafieh/obsidian-list-modified/files/8406671/test.md)
> 
>     * [test 1.md](https://github.com/franciskafieh/obsidian-list-modified/files/8406669/test.1.md)
> 
> 
> Edits to `test.md` **always** get added to the daily note. Edits to its copy, `test 1.md`, are _**never**_ added to the daily note.

can't reprod any of these issues... maybe i've already fixed it and didn't push? going to push once i finish another feature (hopefully in under half an hr) and lmk if the new version works

here's my testing....

https://user-images.githubusercontent.com/93789670/161637875-1cffdbfc-47f2-49ad-b329-dd779cad7394.mp4

**Comment by franciskafieh** [comment] 2022-04-04 22:12
temporary new version: https://www.file.io/liL0/download/YfMEr9TVVq1r

just replace the current main.js file with this. no need to change the manifest.json, since there's no new version yet

**Comment by ScottKillen** [comment] 2022-04-05 03:04
☹️ File was deleted!

**Comment by franciskafieh** [comment] 2022-04-05 11:03
> ☹️ File was deleted!

not sure why, but github won't let me upload a js file! i think i found your discord from the obsidian server, i'll dm it to you there

**Comment by ScottKillen** [comment] 2022-04-05 16:00
Got it!

**Comment by ScottKillen** [comment] 2022-04-05 16:16
So we have a regression on this new version...It is not taking into account the folder setting in the Daily note plugin...so, it can't find my daily note anymore...

![image](https://user-images.githubusercontent.com/1509989/161799378-86c018b9-96a7-4424-96eb-c1fd39f50c64.png)

**Comment by franciskafieh** [comment] 2022-04-05 16:22
> So we have a regression on this new version...It is not taking into account the folder setting in the Daily note plugin...so, it can't find my daily note anymore...
> 
> ![image](https://user-images.githubusercontent.com/1509989/161799378-86c018b9-96a7-4424-96eb-c1fd39f50c64.png)
> 
> 

Should be easy to fix

**Comment by franciskafieh** [comment] 2022-04-05 17:50
Fixed in https://github.com/franciskafieh/obsidian-list-modified/commit/304e651dfad92ebe54b4f875d1395fe71ad88eec from my tests... going to build and create a new temporary release since I can't access discord atm

**Comment by franciskafieh** [comment] 2022-04-05 17:54
@ScottKillen could you try [release 1.0.1](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/1.0.1) for me?

**Comment by ScottKillen** [comment] 2022-04-05 20:36
Unfortunately, it still cannot find my daily note.

**Comment by franciskafieh** [comment] 2022-04-05 20:50
> Unfortunately, it still cannot find my daily note.

that's really odd because it seems to be working for me with the exact same setup...

![image](https://user-images.githubusercontent.com/93789670/161846587-b556f8be-e703-4323-9fe7-ee806bbc666b.png)

![image](https://user-images.githubusercontent.com/93789670/161846644-14b31a4c-f5e4-4da9-8eab-2afaf1600fd9.png)

![image](https://user-images.githubusercontent.com/93789670/161846695-a74f24cd-39c5-4151-8b57-abd4ac126dd2.png)



are there any errors in console?

**Comment by franciskafieh** [comment] 2022-04-05 20:56
whoops, found a bug i need to fix... should not affect the file not being found for you, though. maybe it will fix itself whenever i release version 1.1 somehow..?

**Comment by ScottKillen** [comment] 2022-04-05 21:00
I'm not sure why...  🤔

**Comment by franciskafieh** [comment] 2022-04-05 21:00
also, another troubleshooting method: could you try pasting `this.app.vault.getAbstractFileByPath(moment().format('[Daily Notes]/YYYY/MM-MMMM/YYYY-MM-DD') + ".md")` into console? it should return something like this if that file exists...

![image](https://user-images.githubusercontent.com/93789670/161848294-b3ccec29-ad5b-401a-b5bd-9d89887350b0.png)

otherwise, it may say `undefined`

**Comment by franciskafieh** [comment] 2022-04-08 15:10
Any updates on the issue?

**Comment by ScottKillen** [comment] 2022-04-09 05:14
Sorry, I am currently working about 18 hours a day...

Probably won't get time for a few weeks.

**Comment by franciskafieh** [comment] 2022-04-09 13:40
That's ok. When you do have time, feel free to test again. No rush! Going
to close this for now, since I cannot reproduce, but please re-open if the
issue persists on v1.1!

**Closed** 2022-04-09 13:43 UTC
Labels: bug

**Comment by ScottKillen** [comment] 2022-04-09 13:55
I did upgrade to the latest release this morning, and so far, I have not seen the weirdness 😄
