### ISSUE TITLE
[FR] enable/disable per system in plugin settings

### ISSUE THREAD

**Issue by garbosz** [franciskafieh/obsidian-list-modified#103] opened 2024-08-23 00:32 UTC
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature
much like how the github plugin, id like to see an option to disable functionality of the plugin on a per system basis, that way i could obsidian running on multiple systems and designate only one to write and track the list of modified files without having to deal with multiple computers having sync discrepancies or having to disable other sync settings to acheive the same effect
Please provide a clear description of the feature.

## Possible alternatives
you could disable active community plugin list in obsidian sync to manually turn off the plugin to achieve the desired effect, but that comes with other downsides like losing the ability to enable or disable other plugins across all systems. 
you could also set a system priority list, so that way if there are any conflicts the user can set which system as the default winner. 
What are some possible alternatives? Have you tried any of them?

## Additional info?
the obsidian git plugin has the exact idea in the plugin settings and i use it in a very similar way to have effectively a master system that handles pushing updated to the github repo and the other systems only have to sync to the master system and it has effectively eliminated all risk for conflicts in my github repos.

**Comment by franciskafieh** [comment] 2024-08-23 20:55
> and designate only one to write and track the list of modified files 

obsidian list modified (3.x least) should not write files which are synced to the modified list. It only considers files modified by the user to be eligible.

> the obsidian git plugin has the exact idea in the plugin settings

Thank you for this. I was trying to figure out how a feature like this would work (see #84) but could not figure it out. I looked at [the Obsidian Git code](https://github.com/Vinzent03/obsidian-git/blob/5ea80f66021c6469e6f57eeedf063e804eb751f9/src/setting/settings.ts#L761-L773) and I understand that it just uses local storage so the setting does not sync.

Are you on 3.0.0? In my eyes, I still don't see why you would want to disable List Modified on one device, since in this version (in alpha release right now) your files should not be marked as modified if they are synced from another device. If you are on 3.0.0 and this is still an issue for you, I will definitely implement it

**Comment by garbosz** [comment] 2024-08-24 04:43
interesting, the plugin library inside obsidian shows 2.2.3 as the latest version and checking for updates/reinstalling the plugin doesnt see 3.0.0. only 2.2.3. the behavior i see is if i leave obsidian open on my home computer, and then go to work and open the same vault on my work computer, theyll basically disagree which files were modified when, which ends up with a loop of one system removing an entry from the list modified changelog and the other system putting back over and over again.

**Comment by franciskafieh** [comment] 2024-08-24 11:34
> the plugin doesnt see 3.0.0. only 2.2.3
You need to manually install 3.0.0, since it is in alpha right now. [Here are the instructions and important info to read before upgrading](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/3.0.0-alpha). Let me know how it goes

**Comment by technotherion** [comment] 2024-08-25 21:42
A suggestion @garbosz , check out [Plugin Groups](https://github.com/Mocca101/obsidian-plugin-groups). This will allow you to disable any plugin on a different system.

**Comment by garbosz** [comment] 2024-08-26 04:29
> A suggestion @garbosz , check out [Plugin Groups](https://github.com/Mocca101/obsidian-plugin-groups). This will allow you to disable any plugin on a different system. 

This looks really promising thanks for the suggestion.

**Comment by franciskafieh** [comment] 2024-08-26 16:23
Any updates? If your issue is solved, I will close it as a duplicate of #91

**Closed** 2024-08-31 14:04 UTC
