### ISSUE TITLE
[BUG] Excluded Folders Bug

### ISSUE THREAD

**Issue by overkill864** [franciskafieh/obsidian-list-modified#60] opened 2022-12-26 03:57 UTC
## Describe the bug

List Modified does not respect excluded folders or Ignored Name Text. 

## Expected behaviour
When I put any variation of a folder name whether /Daily or Daily or Daily/ or /Daily it still pulls files from Daily and puts them in the list. 
What should happen instead?
It should not pull files. 
## Reproducing
Unless I am not structuring format correctly, but I even tested using the exact system in the wiki. Not having any luck excluding folders, ignored tags work though but I don't use tags.

**Comment by franciskafieh** [comment] 2022-12-26 04:04
This is odd. Do you happen to know if this was reproducible on a previous version of the plugin?

I've been meaning to update this plugin for awhile, but I haven't had the time to sit down because I'm working on so many other things

**Comment by franciskafieh** [comment] 2022-12-26 04:09
Edit: Just tried on v2.0.1 and folder exclusions seem to be working for me. I simply put "Daily" (no quotation marks) in the settings, and files within it are properly excluded. Could you please take a screenshot of your vault folder structure (e.g. below) and your exclusion settings?
![image](https://user-images.githubusercontent.com/93789670/209498700-3beddf52-e585-4fc6-a3fe-48086900ea28.png)

**Comment by overkill864** [comment] 2022-12-27 17:18
Coming back to it now all the functionality is working. Maybe I'm having trouble with mobile only. I will look into this more. Thanks for your help!

**Comment by overkill864** [comment] 2022-12-27 17:39
So what might be happening is that I have Obsidian sync running. When I make changes to my plugin, even though I have all settings being synced, it doesn't seem to actually sync in real time. So what seems to be happening is when I alter the plugin settings, it works, then all of the sudden a minute or so later it shows up again, then a minute later it disappears. I suspect another version of obsidian on my computer at work is overwriting what my version here is writing. Then it goes back and forth constantly.

**Comment by franciskafieh** [comment] 2022-12-27 18:28
Hmm,that is possible, although I'm not sure as I have no experience with Sync. If you haven't found an answer yet, I would recommend asking in the Obsidian Discord or on their forums. Closing this for now, but if there is anything else I could do to assist you, feel free to re-open.

**Closed by franciskafieh** 2022-12-27 18:28 UTC
Labels: question
