### ISSUE TITLE
[BUG] Header is still not recognized

### ISSUE THREAD

**Issue by oliviercarizzoni** [franciskafieh/obsidian-list-modified#64] opened 2023-01-13 15:15 UTC
Spams notications of title not recognized are still there when daily note is created, whatever the title or title level we put :

![image](https://user-images.githubusercontent.com/36270849/212353518-60712fac-8afc-4538-abd3-40f5827b9ce0.png)

Links get duplicated in note, but somehow the content gets normalized once we modify notes and the plugin is reacting and updating the daily note.

To be honest, i ran through some nightmare with this plugin since early versions 😅, but the idea is very good. Maybe implementation is overcomplicated ?

**Comment by franciskafieh** [comment] 2023-01-13 15:29
Although I cannot replicate this, I'm reworking the entire plugin ATM. I've just been very busy recently because I was participating in a hackathon and I have exams coming up. Hopefully I can get it out this weekend, but I hate making promises because they are often out of my control in these situations.

The reason it is overcomplicated is because there are many features people like (e.g. choosing a header, have separate sections for created and deleted files, note criteria.) It's difficult to keep the implementation simple with all these 

I'm working on modularizing all the code to make it easier to work with and expand. I had originally implemented it in a "script-like" way because I had never expected this many feature requests, but it turns out that it was a bad idea lol

Once I finish 2.1, it might "fix" this bug that I cannot re-produce ATM, but might be caused by, for example, an error in your data.json.

For now, if you want something simple, you can use a dataview query that lists files with a file.mday that is the same as the day in your daily note. The reason I made this plugin was to persist the modified date past the likes of Obsidian.

**Comment by oliviercarizzoni** [comment] 2023-01-13 15:33
Allright thanks anyway for you detailed answer and your work here, good luck for exams ! Take your time and do what you can :)

**Comment by franciskafieh** [comment] 2023-01-15 16:58
> Hopefully I can get it out this weekend, but I hate making promises because they are often out of my control in these situations.
Since this comment, I've been assigned 2 more major projects lol. Think I'm gonna have to put this project on hold until February. Will add a notice to the readme.

**Comment by franciskafieh** [comment] 2023-02-13 01:48
This should be fixed in 2.1 which will release soon (just need to finish testing.) If not, please re-open this.

**Closed by franciskafieh** 2023-02-13 01:48 UTC

**Comment by franciskafieh** [comment] 2023-02-13 05:35
Just released 2.1: https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.1. Feel free to take a look and report back!

**Comment by jfgrtsn** [comment] 2023-02-13 23:53
I'm confused. My day notes don't have an H1 because Obsidian displays the filename at the top. My template has an H2 (## Touched) where created and modified files should be listed. I can't figure out how to accomplish that with the new options.

**Comment by franciskafieh** [comment] 2023-02-14 00:43
> I'm confused. My day notes don't have an H1 because Obsidian displays the filename at the top. My template has an H2 (## Touched) where created and modified files should be listed. I can't figure out how to accomplish that with the new options.

Currently, the parser is formatted in a way where your "primary" heading has to be H1, and your secondary has to be H2 (which is auto-generated anyway). I might make this a little more flexible eventually, but this is the easiest way for now.

**Comment by franciskafieh** [comment] 2023-02-14 12:28
@jfgrtsn, see #69
