### ISSUE TITLE
[BUG] When Obsidian indexes synced files, they are marked as modified

### ISSUE THREAD

**Issue by MMoMM-org** [franciskafieh/obsidian-list-modified#91] opened 2024-02-29 11:08 UTC
Problem Statement:

1. I'm using different sync mechanism for different vaults. (Box, iDrive, ObsidianSync)
2. I'm not running Obsidian all the time on all devices (Dual Boot)
3. Sometimes Obsidians "forgets" the vault exists or things it needs to re-index it.
4. Both 2. and 3. trigger a massive number of updated notes for that day

Example:
I did use my Work Obsidian (which is syncing via BOX but that isn't the real issue) for 2 weeks on my work laptop. After that I shut it down. 
I than wait for Box to stop syncing on my work PC.
I start Obsidian. Now there are 2 options of what will happen. Either 2. or 3. from above.
If 2.
- List Modified things that all notes created between the last time the plugin was run on my work PC till today are modified
if 3.
- List Modified things that ALL notes ever created in my vault are modified.

I think there could be 3 ways to remove the problem.
For Issue 2.
- Make sure that a flag which is synced by all Sync Services (at least filebased and Obsidian Sync) is used as a starting point for which files are changed
For Issue 2 and 3.
- Only track changes after the plugin was loaded, not since the beginning of the cutoff date.
- This would probably also require a little waiting time, as if people using Obisdian Sync new/modified files will take some time to be synced.
For Issue 2 and 3.
- Only track file changes via the Obsidian API, not based on file modified date.
- I'm using https://github.com/beaussan/update-time-on-edit-obsidian which only updates file when they are edited, that might be an option.
- On the other side this would mean that changes outside of obsidian could not be tracked

**Comment by franciskafieh** [comment] 2024-03-02 05:19
Took a quick look at the plugin you linked. The method OLM uses to track files is the same. Outside modifications and sync stuff should not be tracked unless Obsidian is open before the files are synced. OLM also does not track files based on their modification dates.

Is there any way you can get your files to sync before you open Obsidian? If so, could you try this and let me know if it resolves your issue?

> Make sure that a flag which is synced by all Sync Services (at least filebased and Obsidian Sync) is used as a starting point for which files are changed

Not sure what you mean here. Could you expand on this please?

**Comment by MMoMM-org** [comment] 2024-03-04 13:23
That is weird as I know it will think that notes are updated if you use OneDrive etc as sync service. Also I can't let the notes sync before as I'm also using Obsidian Sync, that only runs if Obsidian is running.

To me it looks like that OLM tracks somewhere the last time it was run. And this information is not synced to other instances, neither with OneDrive etc nor with Obsidian Sync.

I think that this is the case because if I work on my computer and turn it off, then use my laptop for 2 weeks, then switch off the laptop, turn on the compter, OLM on the computer instance will find all the notes which were created during those 2 weeks as modified / new. Keep in mind that OLM is running also on the laptop during that time.

**Comment by MMoMM-org** [comment] 2024-03-05 11:19
It just came to my mind. Could it be that this is a "feature"/bug in Obsidian? Indexing shouldn't cause a modified event.
So if Obsidian fires a modified event every time it sees new files (either before or after Obsidian starts) or when it reindexs the vault, the result of OLM would make sense. It would also explain the behaviour I see.
Update Time on Edit probably doesn't has the issue as it only works in the note you have open.
What do you think?

**Comment by franciskafieh** [comment] 2024-03-07 00:38
> Could it be that this is a "feature"/bug in Obsidian? Indexing shouldn't cause a modified event.
So if Obsidian fires a modified event every time it sees new files (either before or after Obsidian starts) or when it reindexs the vault

I believe this is true but I would need to test further. It's weird that you're the first person opening an issue on this, though, with all the people that use this plugin with Obsidian sync. I will need to look into it further in the next coming weeks. I am very busy at the moment

**Comment by ChrisKolan** [comment] 2024-04-15 10:48
I can confirm this problem. I use Syncthing to synchronize my notes between machines. This happens every time re-indexing is activated.

**Comment by franciskafieh** [comment] 2024-04-19 17:51
Sorry for the late reply, I have been very busy lately.

As I mentioned before:
> Is there any way you can get your files to sync before you open Obsidian? If so, could you try this and let me know if it resolves your issue?

Otherwise, I am currently unsure how to solve this. The Obsidian modification API is very limited. There is no way to tell in which way the obsidian files have been modified (whether it be the user vs the sync service, for example)

**Comment by franciskafieh** [comment] 2024-04-19 17:55
One possible solution could be a setting to disable OLM to by default, until you manually turn it on from settings. This could be done automatically if there is a way to tell when SyncThing, same for any other sync service

**Comment by ChrisKolan** [comment] 2024-04-21 21:13
When I use Syncthing, the files are always synchronized, before I open Obsidian, I always check that this is the case. So I think there is some other effect at play here. 
As I mentioned, the problem occurs during indexing. I don't know exactly what triggers the indexing, but I have noticed that the indexing occurs when one of the computers has been switched off for a long time. The longer it has been off, the longer the indexing and also the longer list of the the changes in OLM.

**Comment by MMoMM-org** [comment] 2024-04-26 08:49
Perhaps adding a configurable delay could help? I know that this will not cover all cases but might be an option.
Or allow editing of the list OLM creates, atm it is quite stubborn and I need to edit the list the day after.

**Comment by franciskafieh** [comment] 2024-04-26 13:08
I just had an idea that would probably cover most cases. If more than 5
files are added at once, it won’t track all files modified with a few
seconds until they are edited again. I think this would be a good idea, and
I would make it toggleable.

Being able the edit the list is a feature I would work on eventually, but I
haven’t even had time recently to work on core bug fixes. School has been
super busy lately

**Comment by ChrisKolan** [comment] 2024-04-29 19:49
As @MMoMM-org mentioned "Perhaps adding a configurable delay could help?". This could potentially solve the problem. When obsidian starts up and indexes, OLM should be turned off and on after some time.

**Comment by franciskafieh** [comment] 2024-04-29 19:56
works for me. that’s an easier solution than what I proposed anyway

**Comment by franciskafieh** [comment] 2024-06-25 19:46
Waiting for advice from Obsidian staff as to how a delay could be properly configured.

**Comment by franciskafieh** [comment] 2024-06-25 23:06
![image](https://github.com/franciskafieh/obsidian-list-modified/assets/93789670/dc468d4b-1eed-4d19-bdbc-2eb1fe333e57)
note to self: possible fix that would not require the bandaid solution of a delay period...

Once 3.0 is released in beta, I will let you all know and you can see if it fixes the issue.

**Comment by franciskafieh** [comment] 2024-06-27 00:37
@ChrisKolan @MMoMM-org can one of you add me on Discord (francoiss.) so that I can further diagnose this issue? I want to do some testing for a possible solution

**Comment by franciskafieh** [comment] 2024-06-27 00:59
Nevermind. All is well. The current solution uses the file's system modification time. As long as Obsidian is not opened until all files are synced, this solution should be sufficient. Does this sound fair?

**Comment by garbosz** [comment] 2024-07-26 17:39
im still experiencing this bug where its linking to all 898 files in my vault after one of my machines re indexed, is there a way to manually flush the queue and reset the plugin for the day?

**Comment by franciskafieh** [comment] 2024-07-26 18:52
Sorry, this bug fix is not yet released (as per the "fix pending" tag). I have not yet had time to finish this version, so it is not ready for release. For now, you can manually flush the queue by closing Obsidian first, then head to your obsidian vault's folder > .obsidian > plugins > obsidian-list-modified > open data.json in a text editor.

From here, there will be a tracked files section. This will look like the following:

```json
trackedFiles: [{a bunch of stuff in here}, {spanned over a bunch of lines}]
```

replace it with

```json
trackedFiles: []
```

remember to save the file after doing this. Now, reopen Obsidian. Make an edit to a file and your modified files list should now be empty.

**Closed** 2024-08-11 13:37 UTC
Labels: confirmed bug, question, sync issue, fix pending release
